import { IBookdetail } from './../interfaces/book-details';
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Injectable({
  providedIn: 'root'
})
export class BookDetailsService {

  constructor(private http: HttpClient) { }

  getBookDetails() {
    return [
      {ISBN: '8425679125', bookName: 'Masterguide-Physics for GCE A/L', author: 'n/a',
       publisher: 'Godage', mediumType: 'English', examType: 'A/L', subject: 'Physics', price: 450, itemType: 'Reference Book', copies: 1},
      {ISBN: '7541289642', bookName: 'My Tutor - Chemistry GCE A/L', author: 'n/a',
      publisher: 'Godage', mediumType: 'Sinhala', examType: 'A/L', subject: 'Chemistry', price: 850, itemType: 'Reference Book', copies: 1},
      {ISBN: '4851236975', bookName: 'Fundamentals of Business Logic', author: 'T. Stevenson', publisher: 'Sarasavi', mediumType: 'English', examType: 'A/L', subject: 'Business Studies', price: 1520, itemType: 'Reference Book', copies: 1},
      {ISBN: '1546927851', bookName: 'Tales of Shakespear', author: 'Shakespear',
       publisher: 'Godage', mediumType: 'English', examType: 'O/L', subject: 'English Literature', price: 1200, itemType: 'Reference Book', copies: 1},
      {ISBN: '7854123658', bookName: 'A Guide to Geology', author: 'L. Nelson',
       publisher: 'Sarasavi', mediumType: 'English', examType: 'O/L', subject: 'Geology', price: 1540, itemType: 'Reference Book', copies: 1},
      {ISBN: '4518245875', bookName: 'Sinhala Sahithya', author: 'D. Paranawithana',
       publisher: 'Sarasavi', mediumType: 'Sinhala', examType: 'O/L', subject: 'Sinhala Language', price: 640, itemType: 'Reference Book', copies: 1},
      {ISBN: '1489654254', bookName: 'Organic Chemistry', author: 'T.M. Rodrigo',
       publisher: 'Rathna Publishers', mediumType: 'Sinhala', examType: 'A/L', subject: 'Chemistry', price: 1100, itemType: 'Reference Book', copies: 1},
      {ISBN: '2564785235', bookName: 'History and Geology', author: 'Y.G. Withana',
       publisher: 'The Sri Lankan', mediumType: 'Sinhala', examType: 'O/L', subject: 'History', price: 725, itemType: 'Reference Book', copies: 1},
      {ISBN: '3248571266', bookName: 'Hydrogen and the halogens', author: 'T.S. Viens',
       publisher: 'Penguin Books', mediumType: 'English', examType: 'A/L', subject: 'Chemistry', price: 2460, itemType: 'Reference Book', copies: 1},
      {ISBN: '6577415895', bookName: 'Inorganic Chemistry', author: 'T.H. Nelson',
       publisher: 'Godage Books', mediumType: 'English', examType: 'A/L', subject: 'Chemistry', price: 2200, itemType: 'Reference Book', copies: 1},
      {ISBN: '7548125632', bookName: 'My Tutor - Calculus Guide', author: 'n/a',
       publisher: 'Sarasavi Publications', mediumType: 'Sinhala', examType: 'A/L', subject: 'Combined Mathematics', price: 980, itemType: 'Reference Book', copies: 1},
      {ISBN: '3245718526', bookName: 'Business Analytics', author: 'L. Williamson',
       publisher: 'Stamford Lake Publications', mediumType: 'English', examType: 'A/L', subject: 'Business Studies', price: 3150, itemType: 'Reference Book', copies: 1},
      {ISBN: '4512785469', bookName: 'Business Economics', author: 's. Rathna',
       publisher: 'Godage Publications', mediumType: 'Sinhala', examType: 'A/L', subject: 'Economics', price: 845, itemType: 'Reference Book', copies: 1},
      {ISBN: '4215785412', bookName: 'Geometry', author: 'Owen Wilson',
       publisher: 'The Modern Book Company', mediumType: 'English', examType: 'O/L', subject: 'Maths', price: 1200, itemType: 'Reference Book', copies: 1},
      {ISBN: '1425795548', bookName: 'A Complete Guide to Visual Basic', author: 't.H Stevenson',
       publisher: 'The Modern Book Company', mediumType: 'English', examType: 'A/L', subject: 'IT', price: 1650, itemType: 'Reference Book', copies: 1},
      {ISBN: '8745125468', bookName: 'Trigonometry', author: 'S.L. Looney', publisher: 'Sarasavi Publications', mediumType: 'English', examType: 'A/L', subject: 'Combined Mathematics', price: 1230, itemType: 'Reference Book', copies: 1},
      {ISBN: '1544751125', bookName: 'Art history', author: 'J.K. Rathnayake',
       publisher: 'Tikiri Publications', mediumType: 'Sinhala', examType: 'A/L', subject: 'Art', price: 860, itemType: 'Reference Book', copies: 1},
      {ISBN: '5214879651', bookName: 'Combined Maths Syllabus Guide', author: 'n/a',
       publisher: 'Sarasavi Publications', mediumType: 'Sinhala', examType: 'A/L', subject: 'Combined Mathematics', price: 750, itemType: 'Reference Book', copies: 1},
      {ISBN: '6245215775', bookName: 'Combined Maths Syllabus Guide', author: 'n/a',
       publisher: 'Sarasavi Publications', mediumType: 'Tamil', examType: 'A/L', subject: 'Combined Mathematics', price: 750, itemType: 'Reference Book', copies: 1},
      {ISBN: '7548125489', bookName: 'Management Accounting', author: 'Piyasena',
       publisher: 'Sarasavi Publications', mediumType: 'Sinhala', examType: 'A/L', subject: 'Accounting', price: 1250, itemType: 'Reference Book', copies: 1},
      {ISBN: '1542578512', bookName: 'Science Textbook', author: 'L.A. Rathnasiri',
       publisher: 'Godage Publications', mediumType: 'English', examType: 'O/L', subject: 'Science', price: 995, itemType: 'Reference Book', copies: 1},
      {ISBN: '3254697751', bookName: 'Jane Eyre', author: 'Charlotte Bronte',
       publisher: 'Smith, Elder & Co.', mediumType: 'English', examType: 'O/L', subject: 'English Literature', price: 1500, itemType: 'Reference Book', copies: 1},
      {ISBN: '1546945122', bookName: 'Health and Safety', author: 'T. Sensu',
       publisher: 'Rathna Publications', mediumType: 'Sinhala', examType: 'O/L', subject: 'Health Studies', price: 670, itemType: 'Reference Book', copies: 1},
      {ISBN: '7548125462', bookName: 'Physics Past Papers 1990-2018', author: 'n/a',
       publisher: 'Sarasavi Publications', mediumType: 'English', examType: 'A/L', subject: 'Physics', price: 750, itemType: 'Past Papers', copies: 1},
      {ISBN: '1452879654', bookName: 'Chemistry Past Papers 2005-2018', author: 'n/a',
       publisher: 'Rathna Publishers', mediumType: 'Sinhala', examType: 'A/L', subject: 'Chemistry', price: 1100, itemType: 'Past Papers', copies: 1},
      {ISBN: '2547995654', bookName: 'Combined Mathematics Past Papers 1975-1999', author: 'n/a',
       publisher: 'Tikiri Publications', mediumType: 'Tamil', examType: 'A/L', subject: 'Combined Mathematics', price: 856, itemType: 'Past Papers', copies: 1},
      {ISBN: '3254785125', bookName: 'Business Studies Past Papers 2000-2018', author: 'n/a',
       publisher: 'Sarasavi Publications', mediumType: 'English', examType: 'O/L', subject: 'Commerce', price: 788, itemType: 'Past Papers', copies: 1},
      {ISBN: '6547854214', bookName: 'Business Economics Past Papers', author: 'n/a',
       publisher: 'Rathna Publishers', mediumType: 'Tamil', examType: 'A/L', subject: 'Economics', price: 960, itemType: 'Past Papers', copies: 1},
      {ISBN: '9548712582', bookName: 'Sinhala Language and Literature Past Papers', author: 'n/a',
       publisher: 'Tikiri Publications', mediumType: 'Sinhala', examType: 'O/L', subject: 'Sinhala Language', price: 750, itemType: 'Past Papers', copies: 1},
      {ISBN: '1245785469', bookName: 'English Language Past Papers', author: 'n/a',
       publisher: 'Sarasavi Publications', mediumType: 'English', examType: 'O/L', subject: 'English Language', price: 750, itemType: 'Past Papers', copies: 1},
      {ISBN: '3245718526', bookName: 'Biology Past Papers 1990-2018', author: 'n/a',
       publisher: 'Sarasavi Publications', mediumType: 'English', examType: 'A/L', subject: 'Biology', price: 1100, itemType: 'Past Papers', copies: 1},
      {ISBN: '4578125478', bookName: 'Combined Maths Past Papers 2000-2017', author: 'n/a',
       publisher: 'Tikiri Publications', mediumType: 'Sinhala', examType: 'A/L', subject: 'Combined Mathematics', price: 965, itemType: 'Past Papers', copies: 1},
      {ISBN: '2154798426', bookName: 'History O/L Past Papers', author: 'n/a',
       publisher: 'Sarasavi Publications', mediumType: 'Tamil', examType: 'O/L', subject: 'History', price: 850, itemType: 'Past Papers', copies: 1},
      {ISBN: '3214578456', bookName: 'O/L Science Past Papers', author: 'n/a',
       publisher: 'Sarasavi Publications', mediumType: 'Tamil', examType: 'O/L', subject: 'Science', price: 950, itemType: 'Past Papers', copies: 1},
      {ISBN: '1246987525', bookName: 'IT Past Papers', author: 'n/a',
       publisher: 'Rathna Publishers', mediumType: 'Sinhala', examType: 'A/L', subject: 'IT', price: 950, itemType: 'Past Papers', copies: 1},
      {ISBN: '', bookName: 'Physics Short Notes Complete Set', author: '',
       publisher: '', mediumType: 'English', examType: 'A/L', subject: 'Physics', price: 0, itemType: 'Personal Note', copies: 1},
      {ISBN: '', bookName: 'Science Notes', author: '',
       publisher: '', mediumType: 'Sinhala', examType: 'O/L', subject: 'Science', price: 0, itemType: 'Personal Note', copies: 1},
      {ISBN: '', bookName: 'Maths sample questions and answers', author: '',
       publisher: '', mediumType: 'Sinhala', examType: 'A/L', subject: 'Combined Mathematics', price: 0, itemType: 'Personal Note', copies: 1},
      {ISBN: '', bookName: 'Chemistry Inorganic notes', author: '',
       publisher: '', mediumType: 'English', examType: 'A/L', subject: 'Chemistry', price: 0, itemType: 'Personal Note', copies: 1},
      {ISBN: '', bookName: 'History notes', author: '',
       publisher: '', mediumType: 'Sinhala', examType: 'O/L', subject: 'History', price: 0, itemType: 'Personal Note', copies: 1},
      {ISBN: '', bookName: 'Biology short notes and diagrams', author: '',
       publisher: '', mediumType: 'English', examType: 'A/L', subject: 'Biology', price: 0, itemType: 'Personal Note', copies: 1},
      {ISBN: '', bookName: 'Physics Short Notes Complete Set', author: '',
       publisher: '', mediumType: 'English', examType: 'A/L', subject: 'Physics', price: 0, itemType: 'Short Note', copies: 1},
      {ISBN: '', bookName: 'Science Notes', author: '',
       publisher: '', mediumType: 'Sinhala', examType: 'O/L', subject: 'Science', price: 0, itemType: 'Short Note', copies: 1},
      {ISBN: '', bookName: 'Maths sample questions and answers', author: '',
       publisher: '', mediumType: 'Sinhala', examType: 'A/L', subject: 'Combined Mathematics', price: 0, itemType: 'Short Note', copies: 1},
      {ISBN: '', bookName: 'Chemistry Inorganic notes', author: '',
       publisher: '', mediumType: 'English', examType: 'A/L', subject: 'Chemistry', price: 0, itemType: 'Short Note', copies: 1},
      {ISBN: '', bookName: 'History notes', author: '',
       publisher: '', mediumType: 'Sinhala', examType: 'O/L', subject: 'History', price: 0, itemType: 'Short Note', copies: 1},
      {ISBN: '', bookName: 'Biology short notes and diagrams', author: '',
       publisher: '', mediumType: 'English', examType: 'A/L', subject: 'Biology', price: 0, itemType: 'Short Note', copies: 1}
    ];

  }
}
